### ISSUE TITLE
Bugs affichage GUI report

### ISSUE THREAD

**Issue by EvaliaCraft** [EvaliaCraft-v1/SanctionStaff#1]
C'est la partie main qui prime sur le GUI de report donc même dans le /sanction si je mets comme ceci il me dit 'Menu | Report %name%' alors cela devrait être "&8&lMenu&r &8| Sanction %name%" et la partie : 
 report:
    inv_name: "&8&lMenu&r &8| Report %name%"

Ne fonctionne donc malheureusement pas.

```
  main:
    inv_name: "&8&lMenu&r &8| Sanction %name%"
```
```
  confirm:
    inv_name: "Confirmer l'action: %name%"
  report:
    inv_name: "&8&lMenu&r &8| Report %name%"
    help: "/report <pseudo> : Ouvre l'interface de signalement d'un joueur"
    alert: "&d%name% &ea signalé &c%cible% &epour &7%reason%"
```
